### ISSUE TITLE
Fan Control Startup Issues with 1.0.2 beta

### ISSUE THREAD

**Issue by aaronpotter8556** [iJacks1980/FanControl.CommanderPRO#10]
some feed back. i have found every time i start my pc every single day the commander core is listed as missing senses. in order to fix i have to close FanControl remove the plugin, restart Fancontrol, then close again re-put the plugin back into folder. restart as admin and then it detects the core. and i have set FanControl to run as admin in accessibility options as well.

My Uploads:   (please mind my file host)
Screen Shot: https://mega.nz/file/w7YkQRCY#AVLtGs0iPKUEvpktYEcSk8Q2JBfNAVMPwyNqcAuSuCc
Error Log: https://mega.nz/file/di4gCJ7D#Z_Lb3D8P9dghbh-SzUG0EAHCnixrEJ19VKx8B7k0tHQ
Trace Log: https://mega.nz/file/x2AkwTYC#0H6YOBns4U7hRbDNdClPIRdhJDdlYqEbxjTCbYbHVng

and after first paragraph procedure: https://mega.nz/file/Z252lDib#mUO_z9RPSGezMH6mUcTMDPenWWH7bUWAH5-MKcin1oY 

hope this helps

**Comment by iJacks1980** [comment]
Just a quick update, I **_think_** I have found why it is doing this.  Code is not ready to be released - it's very late and I have work in the morning - but I am hopeful to get a new version out tomorrow evening that will work **_without_** iCUE installed.

**Comment by iJacks1980** [comment]
[Latest beta](https://github.com/iJacks1980/FanControl.CommanderPRO/releases/tag/v1.0.3a) should fix the connection issues.

**Comment by Fishman2294** [comment]
hey aaronpotter would you be able to help me get it to work I can't figure it out

**Comment by Fishman2294** [comment]
do you have discord

**Comment by aaronpotter8556** [comment]
yeap, add me Jace#5804

**Comment by iJacks1980** [comment]
Hope you got this sorted - the reason you were having problems was down to an issue in versions prior to 1.0.3 - there is also a new [version](https://github.com/iJacks1980/FanControl.CommanderPRO/releases/tag/v1.0.4) that works with the latest version of FanControl.
