### ISSUE TITLE
Fan Control > No Plugins Loaded

### ISSUE THREAD

**Issue by quadcom** [iJacks1980/FanControl.CommanderPRO#11]
I popped the dll in the plugins folder and when I went to run the assisted setup, there were no plugins detected.

Let me know if there is a log or anything I can send over to troubleshoot

**Comment by aaronpotter8556** [comment]
did you run FanControl as admin?

**Comment by quadcom** [comment]
I have tried both ways, admin, no admin

Doesn't seem to make a diff.

I am also having issues with FC not matching sensors to fans.

![image](https://user-images.githubusercontent.com/7085931/167219169-11ea3dc8-981c-47a1-9510-9fb9cd26e982.png)

Just writing an issue to FC about it

**Comment by aaronpotter8556** [comment]
have you checked that it isn't been blocked by windows? if it's blocked check the box to un block

**Comment by iJacks1980** [comment]
As aaronpotter8556 said, Windows will probably have blocked the DLL.

Also, what device are you using?  A Commander PRO or CORE?  If using a CORE (or CORE XT) you will want to get the latest pre release version.

**Comment by quadcom** [comment]
Resolved!

First updated my bios. Turned out ot was ancient

Unblocked DLL

Awesome! Goodby Corsair commander and Asus GPU Tweak crapware!!

**Comment by iJacks1980** [comment]
Glad you got it working.  I've just pushed out a new [version](https://github.com/iJacks1980/FanControl.CommanderPRO/releases/tag/v1.0.4) that supports the latest version of FanControl.
