### ISSUE TITLE
Commander Pro - Temperature sensor values too low

### ISSUE THREAD

**Issue by kannan-balasubramanian** [iJacks1980/FanControl.CommanderPRO#13]
I'm facing an issue with temperature sensors and using the latest 1.0.4 version.
I'm also running HWiNFO and wondering if this is causing issues.

Please check the video below.
[Screen capture uploaded to YouTube](https://youtu.be/N8xj9fcvhoc)

**Comment by iJacks1980** [comment]
HwInfo will interfere - it's the nature of how these devices work.  I'm afraid it one or the other, not both.  Realistically there is no way around this - the Commander PRO doesn't have a checksum system so when a request is made for temperature data and another application is also requesting data it's a total chance as to whether you get the right result back - and with no checksum you can't check it's the right data.

Apparently you can turn off "Corsair and Asetek Support" in HwInfo settings to stop it from trying to read Corsair Commander devices.

**Comment by kannan-balasubramanian** [comment]
@iJacks1980 You were correct, the HWiNFO was causing the issue.
