### ISSUE TITLE
Fan control pairs with none

### ISSUE THREAD

**Issue by Tminus89** [iJacks1980/FanControl.CommanderPRO#4]
Hi there. I read the other post and it seems I have that other RGB controller you haven't had in your possession yet (It came with my Obsidian 500D RGB SE). The app sees all fans as it did before installing the plugin. It also shows me the percentages in the 'Control' section. But in 'Speeds' I see 0 rpm with all 6 case fans. The controller shows up in my devices as Commander Pro.  While testing I could not get 1 of the 6 case fans to either ramp up or stop, so it seems there is something preventing it from properly communicating back and forth. As a pc enthusiast with 0 coding knowledge, I could not tell you more at the moment. If there's anything I could check or test out for you to get a better picture I would be glad to help. You're doing a great thing here!!

**Comment by iJacks1980** [comment]
Just looked up that case, and it comes with the Commander PRO (which I had, I've switched over to an H115i with the CORE).

This means the plugin _should_ just work...but there are a few things to check:

1. Do you have Corsair iCUE installed?  If so, uninstall it and try again.  iCUE _will_ cause havoc with the plugin.
2. If uninstalling iCUE does nothing lets check the firmware version.  The easiest way is to use iCUE (yeah the irony is not lost on me), under device it should show the firmware version.  If memory serves mine was on 0.9.212.

Can you also post a screenshot of your Fan Control UI?  That will also give me some idea as to what is happening.

**Comment by Tminus89** [comment]
![Fancontrol UI Tminus89](https://user-images.githubusercontent.com/104441269/165337729-32e3dc81-2a3a-4d88-bfd2-9fa32ab52a45.jpg)
[log.txt](https://github.com/iJacks1980/FanControl.CommanderPRO/files/8564693/log.txt)
1. No I uninstalled it before starting Fancontrol for the first time.
2. Re installed Icue, the firmware version is also 0.9.212. I did not check 
for updates on purpose in case there is one, so we can check things with the one you have.
3. Also after making the screenshot, I selected my gpu and it disappeared all of a sudden. So I added the log file as well

**Comment by iJacks1980** [comment]
Hi Tminus89,

Ok, so looking at the log was interesting...the error messages are all in Dutch ;)  But I recognised enough of the framework details to have an idea as to what is going on.

So lets check a few things.

First has the assembly FanControl.CommanderPro.dll been unblocked?  Right click the file, go to properties and then check the "Unblock this file" checkbox - if there is no checkbox then it's already unblocked.

If that doesn't work try adding <loadFromRemoteSources enabled="true /> to the FanControl.exe.config under the <runtime> node, it will look a little like this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
  </startup>
  <runtime>
    <loadFromRemoteSources enabled="true />
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Numerics.Vectors" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.4.0" newVersion="4.1.4.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by Tminus89** [comment]
Ah so no I didn't unblock it. All case fans are recognized now. I have full control, great. The GPU wasn't able to pair but that was due to MSI Afterburner still having control over it. Disabled the control, retried and it works right away. Thanks a lot! Will donate some cash
