### ISSUE TITLE
do you need another tester?

### ISSUE THREAD

**Issue by aaronpotter8556** [iJacks1980/FanControl.CommanderPRO#9]
hey iJacks1980 do you need another tester for the commander core? i have one with all 6 channels full, 1-3 single fans, 4-6 splitter cables  so 2 fans making 9 in total. i have the 360mm rad version

i don't know much, well basically nothing about coding, but i can stress test it to breaking point with no problems as my main computer it's on can get hot very quickly.

message here if interested, as im offering to help in what ever way i can

**Comment by iJacks1980** [comment]
Your more than welcome to test the 1.0.2 beta release and let me know of any issues you find.
